IMAGE_NAME = python
IMAGE_VERSION = latest
IMAGE_VERSION_ALIASES =
IMAGE_TITLE = Python
IMAGE_DESCRIPTION = Python
IMAGE_SOURCE_URL = https://github.com/scaleway-community/scaleway-python
IMAGE_VENDOR_URL = https://www.python.org/
DEFAULT_IMAGE_ARCH = x86_64
IMAGE_BOOTSCRIPT = mainline 4.9
